#!/usr/bin/env python3
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

from compiler.main import run_file


def main():
    if len(sys.argv) < 2:
        print("Usage: rayvn <file.rv>")
        return

    run_file(sys.argv[1])


if __name__ == "__main__":
    main()